solver:
  warmup_epoch: 5
  base_lr: 0.001
  min_lr: 0.0
  epochs: 30
  weight_decay: 0.0005
  momentum: 0.9
  type: "AdamW"
  fp16: False
dataset:
  data_dir: "/data/tx/MS1MV4"
  batch_size: 128
  num_workers: 16
  num_classes: 93423
  num_image: 5173116
  patch_size: 16
train:
  log_dir: "./logs/"
  show_interval: 1
resume:
  is_resume: True
  resume_path: "/home/power/tx/FaceNeXt/logs/0806_0947_faceNeXt_tiny_finetune/model_5.pth"
model:
  name: "faceNeXt_tiny"
  depth: [ 3, 3, 9, 3 ]
  dims: [ 128, 128, 256, 256 ]
  inner_scale: 1
  s: 64
  m: (1.0, 0.5, 0)
  pretrain_path: "/home/power/tx/FaceNeXt/logs/0730_1709_faceNeXt_tiny_pretrain/model_20.pth"
eval:
  eval_datasets: [ 'lfw', 'agedb_30', 'cfp_fp' ]
#  eval_datasets: [ 'lfw' ]
  bin_root: "/data/tx/MS1MV3/"

print_model: False